### ISSUE TITLE
Do we have a list of what tools are installed when we run the script ?

### ISSUE THREAD

**Issue by aleifuu** [vay3t/hax0rpi#1]

**Comment by vay3t** [comment]
nope, u can view the code for more information

**Comment by hominidae** [comment]
Cursory review of tools installed by the script.

Notable issue is the apt-get install line fails on the current Rasbian Jessie release.

This is likely due to two packages that don't exist in the repository. Suggest removing php5 and ettercap.

You can get it to work by changing ettercap to 'ettercap-text-only'

Also change php5 to 'php' as php7 is the current release.

[15-tools.txt](https://github.com/vay3t/hax0rpi/files/1745746/15-tools.txt)

**Comment by vay3t** [comment]
fixed https://github.com/vay3t/hax0rpi/commit/6156c808914cf8c2d8a4c2be5769e83f38b06bfb
